const SAVE_LOADED_COMPANIES = 'SAVE_LOADED_COMPANIES';
const SAVE_LOADED_SUBDIVISIONS = 'SAVE_LOADED_SUBDIVISIONS';
const SAVE_LOADED_POSITIONS = 'SAVE_LOADED_POSITIONS';
const SET_ACTIVE_COMPANY = 'SET_ACTIVE_COMPANY';
const SET_ACTIVE_SUBDIVISION = 'SET_ACTIVE_SUBDIVISION';

export {
    SAVE_LOADED_COMPANIES,
    SAVE_LOADED_POSITIONS,
    SAVE_LOADED_SUBDIVISIONS,
    SET_ACTIVE_COMPANY,
    SET_ACTIVE_SUBDIVISION
}