const START_LOADING_PAGE = 'START_LOADING_PAGE'
const START_LOADING_POSITIONS = 'START_LOADING_POSITIONS'
const FINISH_LOADING_POSITIONS = 'FINISH_LOADING_POSITIONS'
const FINISH_LOADING_PAGE = 'FINISH_LOADING_PAGE'

export {
    START_LOADING_PAGE,
    START_LOADING_POSITIONS,
    FINISH_LOADING_POSITIONS,
    FINISH_LOADING_PAGE
}