const SHOW_MODAL_WINDOW = 'SHOW_MODAL_WINDOW';
const HIDE_MODAL_WINDOW = 'HIDE_MODAL_WINDOW';
const SHOW_INDICATOR_LIST = 'SHOW_INDICATOR_LIST';
const HIDE_INDICATOR_LIST = 'HIDE_INDICATOR_LIST';
const SHOW_ADD_POSITION_FORM = 'SHOW_ADD_POSITION_FORM';
const HIDE_ADD_POSITION_FORM = 'HIDE_ADD_POSITION_FORM';
const SHOW_EDIT_POSITION_FORM = 'SHOW_EDIT_POSITION_FORM';
const HIDE_EDIT_POSITION_FORM = 'HIDE_EDIT_POSITION_FORM';

export {
    SHOW_MODAL_WINDOW,
    HIDE_MODAL_WINDOW,
    SHOW_INDICATOR_LIST,
    HIDE_INDICATOR_LIST,
    SHOW_ADD_POSITION_FORM,
    HIDE_ADD_POSITION_FORM,
    SHOW_EDIT_POSITION_FORM,
    HIDE_EDIT_POSITION_FORM
}