export const UPDATE_VISIBLE_SUBDIVISIONS = 'UPDATE_VISIBLE_SUBDIVISIONS' 

export const UPDATE_VISIBLE_POSITIONS = 'UPDATE_VISIBLE_POSITIONS' 

export const SUBDIVISIONS_DELETED = 'SUBDIVISIONS_DELETED' 

export const POSITIONS_DELETED = 'POSITIONS_DELETED' 

export const SAVE_LOADED_SUBDIVISIONS = 'SAVE_LOADED_SUBDIVISIONS[UPDATE]' 

export const SAVE_LOADED_POSITIONS = 'SAVE_LOADED_POSITIONS[UPDATE]' 

export const UPDATE_DELETED_SUBDIVISIONS = 'UPDATE_DELETED_SUBDIVISIONS' 

export const UPDATE_DELETED_POSITIONS = 'UPDATE_DELETED_POSITIONS' 

export const RESET_DELETED_SUBDIVISIONS = 'RESET_DELETED_SUBDIVISIONS' 

export const RESET_DELETED_POSITIONS = 'RESET_DELETED_POSITIONS' 

