export const START_LOADING_SUBDIVISIONS = 'START_LOADING_SUBDIVISIONS' 

export const FINISH_LOADING_SUBDIVISIONS = 'FINISH_LOADING_SUBDIVISIONS' 

export const START_LOADING_POSITIONS = 'START_LOADING_POSITIONS' 

export const FINISH_LOADING_POSITIONS = 'FINISH_LOADING_POSITIONS' 

