const SET_EDIT_INDICATOR = 'SET_EDIT_INDICATOR';
const UPDATE_EDIT_INDICATOR_NAME = 'UPDATE_EDIT_INDICATOR_NAME';
const UPDATE_EDIT_INDICATOR_GROUP_ID = 'UPDATE_EDIT_INDICATOR_GROUP_ID';
const RESET_EDIT_INDICATOR = 'RESET_EDIT_INDICATOR';

const SET_EDIT_INDICATOR_GROUP = 'SET_EDIT_INDICATOR_GROUP';
const UPDATE_EDIT_INDICATOR_GROUP_NAME = 'UPDATE_EDIT_INDICATOR_GROUP_NAME';
const UPDATE_EDIT_INDICATOR_GROUP_DESCRIPTION = 'UPDATE_EDIT_INDICATOR_GROUP_DESCRIPTION';
const RESET_EDIT_INDICATOR_GROUP = 'RESET_EDIT_INDICATOR_GROUP';

export {
    SET_EDIT_INDICATOR,
    SET_EDIT_INDICATOR_GROUP,
    UPDATE_EDIT_INDICATOR_GROUP_DESCRIPTION,
    UPDATE_EDIT_INDICATOR_GROUP_ID,
    UPDATE_EDIT_INDICATOR_GROUP_NAME,
    UPDATE_EDIT_INDICATOR_NAME,
    RESET_EDIT_INDICATOR,
    RESET_EDIT_INDICATOR_GROUP
}