const SAVE_INDICATOR_GROUPS = 'SAVE_INDICATOR_GROUPS';
const RESET_INDICATOR_GROUPS = 'RESET_INDICATOR_GROUPS';

const SAVE_INDICATORS = 'SAVE_INDICATORS';
const RESET_INDICATORS = 'RESET_INDICATORS';

const SET_ACTIVE_INDICATOR_GROUP_ID = 'SET_ACTIVE_INDICATOR_GROUP_ID';
const RESET_ACTIVE_INDICATOR_GROUP_ID = 'RESET_ACTIVE_INDICATOR_GROUP_ID';

export {
    SAVE_INDICATORS,
    SAVE_INDICATOR_GROUPS,
    RESET_ACTIVE_INDICATOR_GROUP_ID,
    RESET_INDICATORS,
    RESET_INDICATOR_GROUPS,
    SET_ACTIVE_INDICATOR_GROUP_ID
}