const UPDATE_NEW_INDICATOR_NAME = 'UPDATE_NEW_INDICATOR_NAME';
const UPDATE_NEW_INDICATOR_GROUP_ID = 'UPDATE_NEW_INDICATOR_GROUP_ID';
const RESET_NEW_INDICATOR = 'RESET_NEW_INDICATOR';

const UPDATE_NEW_INDICATOR_GROUP_NAME = 'UPDATE_NEW_INDICATOR_GROUP_NAME';
const UPDATE_NEW_INDICATOR_GROUP_DESCRIPTION = 'UPDATE_NEW_INDICATOR_GROUP_DESCRIPTION';
const RESET_NEW_INDICATOR_GROUP = 'RESET_NEW_INDICATOR_GROUP';

export {
    UPDATE_NEW_INDICATOR_GROUP_DESCRIPTION,
    UPDATE_NEW_INDICATOR_GROUP_ID,
    UPDATE_NEW_INDICATOR_GROUP_NAME,
    UPDATE_NEW_INDICATOR_NAME,
    RESET_NEW_INDICATOR,
    RESET_NEW_INDICATOR_GROUP
}