const UPDATE_POINTED_INDICATORS_FOR_DELETE = 'UPDATE_POINTED_INDICATORS_FOR_DELETE';
const UPDATE_POINTED_INDICATOR_GROUPS_FOR_DELETE = 'UPDATE_POINTED_INDICATOR_GROUPS_FOR_DELETE';

const RESET_POINTED_INDICATOR_GROUPS_FOR_DELETE = '';
const RESET_POINTED_INDICATORS_FOR_DELETE = '';

export {
    UPDATE_POINTED_INDICATORS_FOR_DELETE,
    UPDATE_POINTED_INDICATOR_GROUPS_FOR_DELETE,
    RESET_POINTED_INDICATOR_GROUPS_FOR_DELETE,
    RESET_POINTED_INDICATORS_FOR_DELETE
}