const SET_ADD_INDICATOR_FORM_VISIBLE = 'SET_ADD_INDICATOR_FORM_VISIBLE';
const SET_EDIT_INDICATOR_FORM_VISIBLE = 'SET_EDIT_INDICATOR_FORM_VISIBLE';

const SET_ADD_INDICATOR_GROUP_FORM_VISIBLE = 'SET_ADD_INDICATOR_GROUP_FORM_VISIBLE';
const SET_EDIT_INDICATOR_GROUP_FORM_VISIBLE = 'SET_EDIT_INDICATOR_GROUP_FORM_VISIBLE';

export {
    SET_ADD_INDICATOR_FORM_VISIBLE,
    SET_ADD_INDICATOR_GROUP_FORM_VISIBLE,
    SET_EDIT_INDICATOR_FORM_VISIBLE,
    SET_EDIT_INDICATOR_GROUP_FORM_VISIBLE
}