export const SET_ACTIVE_COMPANY = 'SET_ACTIVE_COMPANY';
export const SAVE_LOADED_COMPANIES = 'SAVE_LOADED_COMPANIES';
export const SAVE_LOADED_VISIBLE_COMPANIES = 'SAVE_LOADED_VISIBLE_COMPANIES';
export const START_LOADING_COMPANIES = 'START_LOADING_COMPANIES';
export const FINISH_LOADING_COMPANIES = 'FINISH_LOADING_COMPANIES';

export const SET_EDIT_COMPANY = 'SET_EDIT_COMPANY';
export const RESET_EDIT_COMPANY = 'RESET_EDIT_COMPANY';
export const SET_EDIT_COMPANY_NAME = 'SET_EDIT_COMPANY_NAME';
export const SET_EDIT_COMPANY_DESCRIPTION = 'SET_EDIT_COMPANY_DESCRIPTION';
export const DELETE_POINTED_ADDED_SUBDIVISIONS = 'DELETE_POINTED_ADDED_SUBDIVISIONS';
export const DELETE_POINTED_SUBDIVISIONS = 'DELETE_POINTED_SUBDIVISIONS';
export const START_DELETING_SUBDIVISIONS = 'START_DELETING_SUBDIVISIONS';
export const FINISH_DELETING_SUBDIVISIONS = 'FINISH_DELETING_SUBDIVISIONS';
export const SAVE_UPDATED_SUBDIVISIONS = 'SAVE_UPDATED_SUBDIVISIONS';
export const UPDATE_POINTED_SUBDIVISIONS = 'UPDATE_POINTED_SUBDIVISIONS';

export const RESET_NEW_COMPANY = 'RESET_NEW_COMPANY';
export const SET_NEW_COMPANY_NAME = 'SET_NEW_COMPANY_NAME';
export const SET_NEW_COMPANY_DESCIRPTION = 'SET_NEW_COMPANY_DESCIRPTION';
export const DELETE_NEW_COMPANY_SUBDIVISIONS = 'DELETE_NEW_COMPANY_SUBDIVISIONS';
export const UPDATE_NEW_COMPANY_POINTED_SUBDIVISIONS = 'UPDATE_NEW_COMPANY_POINTED_SUBDIVISIONS';

export const ADD_SUBDIVISIONS_TO_COPMANY = 'ADD_SUBDIVISIONS_TO_COPMANY';
export const UPDATE_SUBDIVISION_NAME = 'UPDATE_SUBDIVISION_NAME';
export const UPDATE_SUBDIVISION_DESCRIPTION = 'UPDATE_SUBDIVISION_DESCRIPTION';
export const ADD_SUBDIVISION = 'ADD_SUBDIVISION';
export const RESET_ADDING_SUBDIVISION = 'RESET_ADDING_SUBDIVISION';
export const DELETE_SUBDIVISION = 'DELETE_SUBDIVISION';
export const LEAVE_FORM = 'LEAVE_FORM';

export const UPDATE_VISIBLE_SUBDIVISIONS_ADD_FORM = 'UPDATE_VISIBLE_SUBDIVISIONS_ADD_FORM';