export const SAVE_COMPETENCE_GROUPS = 'SAVE_COMPETENCE_GROUPS';
export const SAVE_COMPETENCIES = 'SAVE_COMPETENCIES';
export const SAVE_INDICATOR_GROUPS = 'SAVE_INDICATOR_GROUPS';
export const SAVE_INDICATORS = 'SAVE_INDICATORS';
export const RESET_COMPETENCE_GROUPS = 'RESET_COMPETENCE_GROUPS';
export const RESET_COMPETENCIES = 'RESET_COMPETENCIES';
export const RESER_INDICATOR_GROUPS = 'RESER_INDICATOR_GROUPS';
export const RESET_INDICATORS = 'RESET_INDICATORS';
export const SET_ACTIVE_COMPETENCE_GROUP_ID = 'SET_ACTIVE_COMPETENCE_GROUP_ID';
export const RESET_ACTIVE_COMPETENCE_GROUP_ID = 'RESET_ACTIVE_COMPETENCE_GROUP_ID';
export const SET_ACTIVE_INDICATOR_GROUP_ID = 'SET_ACTIVE_INDICATOR_GROUP_ID';
export const RESET_ACTIVE_INDICATOR_GROUP_ID = 'RESET_ACTIVE_INDICATOR_GROUP_ID';
export const SET_EDIT_COMPETENCE_ID = 'SET_EDIT_COMPETENCE_ID';

