export const SET_ACTIVE_COMPETENCE_GROUP_ID = 'SET_ACTIVE_COMPETENCE_GROUP_ID';
export const SET_ACTIVE_INDICATOR_GROUP_ID = 'SET_ACTIVE_INDICATOR_GROUP_ID';
export const RESET_ACTIVE_COMPETENCE_GROUP_ID = 'RESET_ACTIVE_COMPETENCE_GROUP_ID';
export const RESET_ACTIVE_INDICATOR_GROUP_ID = 'RESET_ACTIVE_INDICATOR_GROUP_ID';
export const RESET_COMPETENCE_GROUPS_FOR_DELETE = 'RESET_COMPETENCE_GROUPS_FOR_DELETE';
export const RESET_COMPETENCIES_FOR_DELETE = 'RESET_COMPETENCIES_FOR_DELETE';
export const UPDATE_COMPETENCE_GROUPS_FOR_DELETE = 'UPDATE_COMPETENCE_GROUPS_FOR_DELETE';
export const UPDATE_COMPETENCIES_FOR_DELETE = 'UPDATE_COMPETENCIES_FOR_DELETE';
