export const SET_ADD_COMPETENCE_FORM_VISIBLE = 'SET_ADD_COMPETENCE_FORM_VISIBLE';
export const SET_ADD_COMPETENCE_GROUP_FORM_VISIBLE = 'SET_ADD_COMPETENCE_GROUP_FORM_VISIBLE';
export const SET_EDIT_COMPETENCE_FORM_VISIBLE = 'SET_EDIT_COMPETENCE_FORM_VISIBLE';
export const SET_EDIT_COMPETENCE_GROUP_FORM_VISIBLE = 'SET_EDIT_COMPETENCE_GROUP_FORM_VISIBLE';
