export const START_LOADING_CONTENT = 'START_LOADING_CONTENT';
export const FINISH_LOADING_CONTENT = 'FINISH_LOADING_CONTENT';

export const START_LOADING_QUESTIONS = 'START_LOADING_QUESTIONS';
export const FINISH_LOADING_QUESTIONS = 'FINISH_LOADING_QUESTIONS';