export const SAVE_LOADED_CONTENT = 'SAVE_LOADED_CONTENT';
export const SAVE_LOADED_QUESTIONS = 'SAVE_LOADED_QUESTIONS';
export const UPDATE_DELETED_QUESTIONS = 'UPDATE_DELETED_QUESTIONS';
export const QUESTIONS_DELETED = 'QUESTIONS_DELETED';
export const RESET_DELETED_QUESTIONS = 'RESET_DELETED_QUESTIONS';