const UPDATE_REQUEST_DATE = 'UPDATE_REQUEST_DATE';
const UPDATE_COMPANY_ID = 'UPDATE_COMPANY_ID';
const UPDATE_SUBDIVISION_ID = 'UPDATE_SUBDIVISION_ID';
const UPDATE_POSITION_ID = 'UPDATE_POSITION_ID';
const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';

const PREPARE_LOADING_COMPANIES = 'PREPARE_LOADING_COMPANIES';
const PREPARE_LOADING_SUBDIVISIONS = 'PREPARE_LOADING_SUBDIVISIONS';
const PREPARE_LOADING_POSITIONS = 'PREPARE_LOADING_POSITIONS';

const FINISH_LOADING_COMPANIES = 'FINISH_LOADING_COMPANIES';
const FINISH_LOADING_SUBDIVISIONS = 'FINISH_LOADING_SUBDIVISIONS';
const FINISH_LOADING_POSITIONS = 'FINISH_LOADING_POSITIONS';

const SAVE_LOADED_COMPAIES = 'SAVE_LOADED_COMPAIES';
const SAVE_LOADED_SUBDIVISIONS = 'SAVE_LOADED_SUBDIVISIONS';
const SAVE_LOADED_POSITIONS = 'SAVE_LOADED_POSITIONS';

const RESET = 'RESET';

export {
    UPDATE_COMPANY_ID,
    UPDATE_DESCRIPTION,
    UPDATE_SUBDIVISION_ID,
    UPDATE_POSITION_ID,
    UPDATE_REQUEST_DATE,

    PREPARE_LOADING_COMPANIES,
    PREPARE_LOADING_SUBDIVISIONS,
    PREPARE_LOADING_POSITIONS,

    FINISH_LOADING_COMPANIES,
    FINISH_LOADING_SUBDIVISIONS,
    FINISH_LOADING_POSITIONS,

    SAVE_LOADED_COMPAIES,
    SAVE_LOADED_POSITIONS,
    SAVE_LOADED_SUBDIVISIONS,

    RESET
}
