const UPDATE_REQUEST_DATE = 'UPDATE_REQUEST_DATE';
const UPDATE_COMPANY_ID = 'UPDATE_COMPANY_ID';
const UPDATE_SUBDIVISION_ID = 'UPDATE_SUBDIVISION_ID';
const UPDATE_POSITION_ID = 'UPDATE_POSITION_ID';
const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
const RESET = 'RESET';

export {
    UPDATE_COMPANY_ID,
    UPDATE_DESCRIPTION,
    UPDATE_SUBDIVISION_ID,
    UPDATE_POSITION_ID,
    UPDATE_REQUEST_DATE,
    RESET
}
