export const UPDATE_VISIBLE_INDICATORS = 'UPDATE_VISIBLE_INDICATORS';
export const UPDATE_VISIBLE_INDICATORS_GROUPS = 'UPDATE_VISIBLE_INDICATORS_GROUPS';

export const SAVE_LOADED_INDICATORS_GROUPS = 'SAVE_LOADED_INDICATORS_GROUPS';
export const SAVE_LOADED_INDICATORS = 'SAVE_LOADED_INDICATORS';

export const INDICATORS_GROUPS_DELETED = 'INDICATORS_GROUPS_DELETED';
export const INDICATORS_DELETED = 'INDICATORS_DELETED';

export const UPDATE_DELETED_INDICATORS = 'UPDATE_DELETED_INDICATORS';
export const RESET_DELETED_INDICATORS = 'RESET_DELETED_INDICATORS';

export const UPDATE_DELETED_INDICATORS_GROUPS = 'UPDATE_DELETED_INDICATORS_GROUPS';
export const RESET_DELETED_INDICATORS_GROUPS = 'RESET_DELETED_INDICATORS_GROUPS';

