export const START_LOADING_INDICATORS = 'START_LOADING_INDICATORS';
export const START_LOADING_INDICATORS_GROUPS = 'START_LOADING_INDICATORS_GROUPS';
export const FINISH_LOADING_INDICATORS = 'FINISH_LOADING_INDICATORS';
export const FINISH_LOADING_INDICATORS_GROUPS = 'FINISH_LOADING_INDICATORS_GROUPS';