export const UPDATE_DELETED_COMPETENCIES = 'UPDATE_DELETED_COMPETENCIES';
export const RESET_DELETED_COMPETENCIES = 'RESET_DELETED_COMPETENCIES';
export const COMPETENCIES_DELETED = 'COMPETENCIES_DELETED';

export const UPDATE_DELETED_COMPETENCIES_GROUPS = 'UPDATE_DELETED_COMPETENCIES_GROUPS';
export const RESET_DELETED_COMPETENCIES_GROUPS = 'RESET_DELETED_COMPETENCIES_GROUPS';
export const COMPETENCIES_GROUPS_DELETED = 'COMPETENCIES_GROUPS_DELETED';

export const SAVE_LOADED_COMPETENCIES_GROUPS = 'SAVE_LOADED_COMPETENCIES_GROUPS';
export const SAVE_LOADED_COMPETENCIES = 'SAVE_LOADED_COMPETENCIES';

export const UPDATE_VISIBLE_COMPETENCIES = 'UPDATE_VISIBLE_COMPETENCIES';
export const UPDATE_VISIBLE_COMPETENCIES_GROUPS = 'UPDATE_VISIBLE_COMPETENCIES_GROUPS';
