const UPDATE_SEARCH_COMPANY_BAR = 'UPDATE_SEARCH_COMPANY_BAR';
const PREPARE_LOADING_COMPANIES = 'PREPARE_LOADING_COMPANIES';
const FINISH_LOADING_COMPANIES = 'FINISH_LOADING_COMPANIES';
const SAVE_LOADED_COMPANIES = 'SAVE_LOADED_COMPANIES';

export {
    UPDATE_SEARCH_COMPANY_BAR,
    PREPARE_LOADING_COMPANIES,
    FINISH_LOADING_COMPANIES,
    SAVE_LOADED_COMPANIES
}