export const UPDATE_NEW_COMPANY_NAME = 'UPDATE_NEW_COMPANY_NAME'
export const UPDATE_NEW_COMPANY_ADDRESS = 'UPDATE_NEW_COMPANY_ADDRESS'
export const NEW_COMPANY_SAVED = 'NEW_COMPANY_SAVED'
export const RESET_NEW_COMPANY = 'RESET_NEW_COMPANY'

export const NEW_COMPANY_NAME_SUCCESS_VALIDATION = 'NEW_COMPANY_NAME_SUCCESS_VALIDATION'
export const NEW_COMPANY_NAME_ERROR_VALIDATION = 'NEW_COMPANY_NAME_ERROR_VALIDATION'
export const NEW_COMPANY_ADDRESS_SUCCESS_VALIDATION = 'NEW_COMPANY_ADDRESS_SUCCESS_VALIDATION'
export const NEW_COMPANY_ADDRESS_ERROR_VALIDATION = 'NEW_COMPANY_ADDRESS_ERROR_VALIDATION'