const SHOW_ADD_NEW_REQUEST_FORM = 'SHOW_ADD_NEW_REQUEST_FORM';
const HIDE_ADD_NEW_REQUEST_FORM = 'HIDE_ADD_NEW_REQUEST_FORM';
const UPDATE_SEARCH_COMPANY_BAR = 'UPDATE_SEARCH_COMPANY_BAR';

export {
    SHOW_ADD_NEW_REQUEST_FORM,
    HIDE_ADD_NEW_REQUEST_FORM,
    UPDATE_SEARCH_COMPANY_BAR
}