const UPDATE_SEARCH_COMPANY_BAR = 'UPDATE_SEARCH_COMPANY_BAR';
const PREPARE_LOADING_REQUESTS = 'PREPARE_LOADING_REQUESTS';
const FINISH_LOADING_REQUESTS = 'FINISH_LOADING_REQUESTS';
const SAVE_LOADED_REQUESTS = 'SAVE_LOADED_REQUESTS';

export {
    UPDATE_SEARCH_COMPANY_BAR,
    PREPARE_LOADING_REQUESTS,
    FINISH_LOADING_REQUESTS,
    SAVE_LOADED_REQUESTS
}