const UPDATE_COMPANY_NAME = 'UPDATE_COMPANY_NAME';
const UPDATE_COMPANY_ADDRESS = 'UPDATE_COMPANY_ADDRESS';
const UPDATE_SUBDIVISION_NAME = 'UPDATE_SUBDIVISION_NAME';
const ADD_ONE_MORE_SUBDIVISION = 'ADD_ONE_MORE_SUBDIVISION';
const SENDING_FORM = 'SENDING_FORM';
const RESET = 'RESET';

export {
    UPDATE_COMPANY_ADDRESS,
    UPDATE_COMPANY_NAME,
    UPDATE_SUBDIVISION_NAME,
    ADD_ONE_MORE_SUBDIVISION,
    SENDING_FORM,
    RESET
}
