const UPDATE_COMPANY_NAME = 'UPDATE_COMPANY_NAME';
const UPDATE_COMPANY_ADDRESS = 'UPDATE_COMPANY_ADDRESS';
const UPDATE_SUBDIVISION_NAME = 'UPDATE_COMPANY_ADDRESS';

export {
    UPDATE_COMPANY_ADDRESS,
    UPDATE_COMPANY_NAME,
    UPDATE_SUBDIVISION_NAME,
    ADD_ONE_MORE_SUBDIVISION,
    REMOVE_SUBDIVISION
}
