const SAVE_LOADED_REQUEST = 'SAVE_LOADED_REQUEST';
const SWITCH_TAB = 'SWITCH_TAB';
const SAVE_LOADED_CANDIDATES = 'SAVE_LOADED_CANDIDATES';
const PREPARE_LOADING_CANDIDATES = 'PREPARE_LOADING_CANDIDATES';
const FINISH_LOADING_CANDIDATES = 'FINISH_LOADING_CANDIDATES';

export {
    SAVE_LOADED_REQUEST,
    SWITCH_TAB,
    SAVE_LOADED_CANDIDATES,
    PREPARE_LOADING_CANDIDATES,
    FINISH_LOADING_CANDIDATES
}