// add COMPETENCIES
export const UPDATE_NEW_COMPETENCE_GROUP_ID = 'UPDATE_NEW_COMPETENCE_GROUP_ID';
export const UPDATE_NEW_COMPETENCE_NAME = 'UPDATE_NEW_COMPETENCE_NAME';

// delete COMPETENCIES
export const UPDATE_DELETED_COMPETENCIES = 'UPDATE_DELETED_COMPETENCIES';
export const RESET_DELETED_COMPETENCIES = 'RESET_DELETED_COMPETENCIES';

// update COMPETENCIES
export const UPDATE_EDIT_COMPETENCE_GROUP_ID = 'UPDATE_EDIT_COMPETENCE_GROUP_ID';
export const UPDATE_EDIT_COMPETENCE_NAME = 'UPDATE_EDIT_COMPETENCE_NAME';

// add group COMPETENCIES
export const UPDATE_NEW_COMPETENCIES_GROUP_NAME = 'UPDATE_NEW_COMPETENCIES_GROUP_NAME';
export const UPDATE_NEW_COMPETENCIES_GROUP_DESCRIPTION = 'UPDATE_NEW_COMPETENCIES_GROUP_DESCRIPTION';

// update COMPETENCIES groups
export const UPDATE_EDIT_COMPETENCIES_GROUP_NAME = 'UPDATE_EDIT_COMPETENCIES_GROUP_NAME';
export const UPDATE_EDIT_COMPETENCIES_GROUP_DESCRIPTION = 'UPDATE_EDIT_COMPETENCIES_GROUP_DESCRIPTION';

// delete groups COMPETENCIES
export const UPDATE_DELETED_COMPETENCIES_GROUPS = 'UPDATE_DELETED_COMPETENCIES_GROUPS';
export const RESET_DELETED_COMPETENCIES_GROUPS = 'RESET_DELETED_COMPETENCIES_GROUPS';

// save
export const SAVE_LOADED_COMPETENCIES_GROUPS = 'SAVE_LOADED_COMPETENCIES_GROUPS';
export const SAVE_LOADED_COMPETENCIES = 'SAVE_LOADED_COMPETENCIES';

// loading
export const START_LOADING_COMPETENCIES = 'START_LOADING_COMPETENCIES';
export const FINISH_LOADING_COMPETENCIES = 'FINISH_LOADING_COMPETENCIES';

// reset form edited and created entities
export const NEW_COMPETENCE_SAVED = 'NEW_COMPETENCE_SAVED';
export const NEW_COMPETENCIES_GROUP_SAVED = 'NEW_COMPETENCIES_GROUP_SAVED';
export const EDIT_COMPETENCE_SAVED = 'EDIT_COMPETENCE_SAVED';
export const EDIT_COMPETENCIES_GROUP_SAVED = 'EDIT_COMPETENCIES_GROUP_SAVED';
export const COMPETENCIES_GROUPS_DELETED = 'COMPETENCIES_GROUPS_DELETED';