const PREPARE_LOADING_GROUPS_ENTITIES = 'PREPARE_LOADING_GROUPS_ENTITIES';
const FINISH_LOADING_GROUPS_ENTITIES = 'FINISH_LOADING_GROUPS_ENTITIES';
const SAVE_LOADED_GROUPS_ENTITIES = 'SAVE_LOADED_GROUPS_ENTITIES';
const SWITCH_TAB = 'SWITCH_TAB';

export {
    SWITCH_TAB,
    PREPARE_LOADING_GROUPS_ENTITIES,
    FINISH_LOADING_GROUPS_ENTITIES,
    SAVE_LOADED_GROUPS_ENTITIES
}