const PREPARE_LOADING_GROUPS_ENTITIES = 'PREPARE_LOADING_GROUPS_ENTITIES';
const FINISH_LOADING_GROUPS_ENTITIES = 'FINISH_LOADING_GROUPS_ENTITIES';
const SAVE_LOADED_GROUPS_ENTITIES = 'SAVE_LOADED_GROUPS_ENTITIES';
const SWITCH_TAB = 'SWITCH_TAB';
const UPDATE_ID_ACTIVE_GROUP_ENTITY = 'UPDATE_ID_ACTIVE_GROUP_ENTITY';
const PREPARE_LOADING_ENTITIES = 'PREPARE_LOADING_ENTITIES';
const SAVE_LOADED_ENTITIES = 'SAVE_LOADED_ENTITIES';
const FINISH_LOADING_ENTITIES = 'FINISH_LOADING_ENTITIES';
const UPDATE_NAME_SEARCH_ENTITY = 'UPDATE_NAME_SEARCH_ENTITY';

export {
    SWITCH_TAB,
    PREPARE_LOADING_GROUPS_ENTITIES,
    FINISH_LOADING_GROUPS_ENTITIES,
    SAVE_LOADED_GROUPS_ENTITIES,
    UPDATE_ID_ACTIVE_GROUP_ENTITY,
    PREPARE_LOADING_ENTITIES,
    SAVE_LOADED_ENTITIES,
    FINISH_LOADING_ENTITIES,
    UPDATE_NAME_SEARCH_ENTITY
}