const FULFIL_INITIAL_LOADING = 'FULFIL_INITIAL_LOADING';
const RESET_INITIAL_LOADING = 'RESET_INITIAL_LOADING';
const START_APPLYING_CHANGES = 'START_APPLYING_CHANGES';
const FINISH_APPLYING_CHANGES = 'FINISH_APPLYING_CHANGES';

export {
    FULFIL_INITIAL_LOADING,
    RESET_INITIAL_LOADING,
    FINISH_APPLYING_CHANGES,
    START_APPLYING_CHANGES
}