// add indicators
export const UPDATE_NEW_INDICATOR_GROUP_ID = 'UPDATE_NEW_INDICATOR_GROUP_ID';
export const UPDATE_NEW_INDICATOR_NAME = 'UPDATE_NEW_INDICATOR_NAME';

// delete indicators
export const UPDATE_DELETED_INDICATORS = 'UPDATE_DELETED_INDICATORS';
export const RESET_DELETED_INDICATORS = 'RESET_DELETED_INDICATORS';

// update indicators
export const UPDATE_EDIT_INDICATOR_GROUP_ID = 'UPDATE_EDIT_INDICATOR_GROUP_ID';
export const UPDATE_EDIT_INDICATOR_NAME = 'UPDATE_EDIT_INDICATOR_NAME';

// add group indicators
export const UPDATE_NEW_INDICATORS_GROUP_NAME = 'UPDATE_NEW_INDICATORS_GROUP_NAME';
export const UPDATE_NEW_INDICATORS_GROUP_DESCRIPTION = 'UPDATE_NEW_INDICATORS_GROUP_DESCRIPTION';

// update indicators groups
export const UPDATE_EDIT_INDICATORS_GROUP_NAME = 'UPDATE_EDIT_INDICATORS_GROUP_NAME';
export const UPDATE_EDIT_INDICATORS_GROUP_DESCRIPTION = 'UPDATE_EDIT_INDICATORS_GROUP_DESCRIPTION';

// delete groups indicators
export const UPDATE_DELETED_INDICATORS_GROUPS = 'UPDATE_DELETED_INDICATORS_GROUPS';
export const RESET_DELETED_INDICATORS_GROUPS = 'RESET_DELETED_INDICATORS_GROUPS';

// save
export const SAVE_LOADED_INDICATORS_GROUPS = 'SAVE_LOADED_INDICATORS_GROUPS';
export const SAVE_LOADED_INDICATORS = 'SAVE_LOADED_INDICATORS';

// loading
export const START_LOADING_INDICATORS = 'START_LOADING_INDICATORS';
export const FINISH_LOADING_INDICATORS = 'FINISH_LOADING_INDICATORS';

// reset form edited and created entities
export const NEW_INDICATOR_SAVED = 'NEW_INDICATOR_SAVED';
export const NEW_INDICATORS_GROUP_SAVED = 'NEW_INDICATORS_GROUP_SAVED';
export const EDIT_INDICATOR_SAVED = 'EDIT_INDICATOR_SAVED';
export const EDIT_INDICATORS_GROUP_SAVED = 'EDIT_INDICATORS_GROUP_SAVED';
export const INDICATORS_GROUPS_DELETED = 'INDICATORS_GROUPS_DELETED';

export const START_LOADING_INDICATORS_GROUPS = 'START_LOADING_INDICATORS_GROUPS';
export const FINISH_LOADING_INDICATORS_GROUPS = 'FINISH_LOADING_INDICATORS_GROUPS';

// search
export const UPDATE_VISIBLE_INDICATORS = 'UPDATE_VISIBLE_INDICATORS';
export const UPDATE_VISIBLE_INDICATORS_GROUPS = 'UPDATE_VISIBLE_INDICATORS_GROUPS';