// questions
export const UPDATE_NEW_QUESTION_BODY = 'UPDATE_NEW_QUESTION_BODY';
export const UPDATE_NEW_QUESTION_COMPETENCE_ID = 'UPDATE_NEW_QUESTION_COMPETENCE_ID';

export const SAVE_LOADED_QUESTIONS_GROUP_CONTENT = 'SAVE_LOADED_QUESTIONS_GROUP_CONTENT';

export const START_LOADING_QUESTIONS_GROUP_CONTENT = 'START_LOADING_QUESTIONS_GROUP_CONTENT';
export const FINISH_LOADING_QUESTIONS_GROUP_CONTENT = 'FINISH_LOADING_QUESTIONS_GROUP_CONTENT';

export const SAVE_LOADED_COMPETENCIES = 'SAVE_LOADED_COMPETENCIES';

export const START_LOADING_QUESTIONS = 'START_LOADING_QUESTIONS';
export const FINISH_LOADING_QUESTIONS = 'FINISH_LOADING_QUESTIONS';
export const SAVE_LOADED_QUESTIONS = 'SAVE_LOADED_QUESTIONS';

export const UPDATE_DELETED_QUESTIONS = 'UPDATE_DELETED_QUESTIONS';

export const QUESTIONS_DELETED = 'QUESTIONS_DELETED';

export const RESET_DELETED_QUESTIONS = 'RESET_DELETED_QUESTIONS';

// validation

export const NEW_QUESTION_COMPETENCE_ID_SUCCESS_VALIDATION = 'NEW_QUESTION_COMPETENCE_ID_SUCCESS_VALIDATION';
export const NEW_QUESTION_COMPETENCE_ID_ERROR_VALIDATION = 'NEW_QUESTION_COMPETENCE_ID_ERROR_VALIDATION';

export const NEW_QUESTION_BODY_SUCCESS_VALIDATION = 'NEW_QUESTION_BODY_SUCCESS_VALIDATION';
export const NEW_QUESTION_BODY_ERROR_VALIDATION = 'NEW_QUESTION_BODY_ERROR_VALIDATION';

export const RESET_NEW_QUESTION_FORM = 'RESET_NEW_QUESTION_FORM';