// questions
export const UPDATE_NEW_QUESTION_BODY = 'UPDATE_NEW_QUESTION_BODY';
export const UPDATE_NEW_QUESTION_GROUP_ID = 'UPDATE_NEW_QUESTION_GROUP_ID';

export const SAVE_LOADED_QUESTIONS_GROUP_CONTENT = 'SAVE_LOADED_QUESTIONS_GROUP_CONTENT';

export const START_LOADING_QUESTIONS_GROUP_CONTENT = 'START_LOADING_QUESTIONS_GROUP_CONTENT';
export const FINISH_LOADING_QUESTIONS_GROUP_CONTENT = 'FINISH_LOADING_QUESTIONS_GROUP_CONTENT';

// questions groups
export const UPDATE_NEW_QUESTIONS_GROUP_NAME = 'UPDATE_NEW_QUESTIONS_GROUP_NAME';
export const UPDATE_NEW_QUESTIONS_GROUP_DESCRIPTION = 'UPDATE_NEW_QUESTIONS_GROUP_DESCRIPTION';
export const UPDATE_EDIT_QUESTIONS_GROUP_NAME = 'UPDATE_EDIT_QUESTIONS_GROUP_NAME';
export const UPDATE_EDIT_QUESTIONS_GROUP_DESCRIPTION = 'UPDATE_EDIT_QUESTIONS_GROUP_DESCRIPTION';
export const SAVE_LOADED_QUESTIONS_GROUPS = 'SAVE_LOADED_QUESTIONS_GROUPS';

export const SAVE_LOADED_COMPETENCIES = 'SAVE_LOADED_COMPETENCIES';

export const START_LOADING_QUESTIONS = 'START_LOADING_QUESTIONS';
export const FINISH_LOADING_QUESTIONS = 'FINISH_LOADING_QUESTIONS';
export const SAVE_LOADED_QUESTIONS = 'SAVE_LOADED_QUESTIONS';

export const UPDATE_DELETED_QUESTIONS = 'UPDATE_DELETED_QUESTIONS';

export const QUESTIONS_DELETED = 'QUESTIONS_DELETED';
export const QUESTIONS_GROUPS_DELETED = 'QUESTIONS_GROUPS_DELETED';

export const UPDATE_DELETED_QUESTIONS_GROUPS = 'UPDATE_DELETED_QUESTIONS_GROUPS';

export const RESET_DELETED_QUESTIONS = 'RESET_DELETED_QUESTIONS';
export const RESET_DELETED_QUESTIONS_GROUPS = 'RESET_DELETED_QUESTIONS_GROUPS';

export const NEW_QUESTIONS_GROUP_SAVED = 'NEW_QUESTIONS_GROUP_SAVED';
export const EDIT_QUESTIONS_GROUP_SAVED = 'EDIT_QUESTIONS_GROUP_SAVED';